# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    config.vm.box = "dmotte/dockerbox"

    config.vm.hostname = "dockerbox01"

    config.vm.provider "virtualbox" do |vb|
        vb.memory = 4096
        vb.cpus = 4
    end

    config.vm.network "private_network", ip: "192.168.56.100"

    config.vm.provision "ansible" do |ansible|
        ansible.playbook = "playbook.yml"
        ansible.extra_vars = { ansible_python_interpreter:"/usr/bin/python3" }
    end

    # Ping the default route once to fix a known network issue. See
    # https://weisser-zwerg.dev/posts/local-discourse-on-vagrant/#vagrant-up
    # for more information
    config.vm.provision "shell", inline: <<-SHELL
        ping 192.168.56.1 -c1
    SHELL
end
