#!/usr/bin/env ansible-playbook
---
- name: Main play
  hosts: all

  pre_tasks:
    - name: Check Ansible version
      ansible.builtin.assert:
        that: ansible_version.full is version_compare('2.9', '>=')
        msg: The Ansible version is too old for this playbook

  tasks:
    - name: Execute apt update if the last one is more than 1 hour ago
      become: true
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
      when: ansible_pkg_mgr == "apt"

    - name: Install Docker and docker-compose
      become: true
      ansible.builtin.package:
        name: [docker.io, docker-compose]

    - name: Add the vagrant user to the docker group
      become: true
      ansible.builtin.user:
        name: vagrant
        groups: [docker]
        append: true

    - name: Reset the Ansible SSH connection to reload the current user's permissions
      # Good practice after adding the user to the docker group
      ansible.builtin.meta: reset_connection
