#!/usr/bin/env ansible-playbook
---
- name: Main play
  hosts: all

  pre_tasks:
    - name: Check Ansible version
      ansible.builtin.assert:
        that: ansible_version.full is version_compare('2.9', '>=')
        msg: The Ansible version is too old for this playbook

  tasks:
    - name: Execute apt update if the last one is more than 1 hour ago
      become: true
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
      when: ansible_pkg_mgr == "apt"

    - name: Install pip and the Docker library for Python
      ansible.builtin.include_role: { name: geerlingguy.pip }
      vars:
        ansible_become: true
        pip_install_packages: [docker]

    - name: Install Docker
      ansible.builtin.include_role: { name: geerlingguy.docker }
      vars:
        ansible_become: true
        docker_users: ["{{ ansible_user }}"]

    - name: Reset the Ansible SSH connection to reload the current user's permissions
      # It's a good practice to reset the connection after including the
      # geerlingguy.docker role, since it adds the ansible_user to the docker group
      ansible.builtin.meta: reset_connection
